--http://technet.microsoft.com/en-us/library/ms173763.aspx
USE [StayHomewithoutPer];

-- Scenario 1

--P1
BEGIN TRANSACTION;
UPDATE Fil
SET city = 'Edinburgh'
  WHERE [Branch ID] = 'B001';

ROLLBACK TRANSACTION;

--P2
SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED;
BEGIN TRANSACTION;
SELECT *
  FROM Fil
  WHERE [Branch ID] = 'B001';
COMMIT TRANSACTION;

SELECT *
  FROM Fil
  WHERE [Branch ID] = 'B001';


--P3
SET TRANSACTION ISOLATION LEVEL READ COMMITTED;

BEGIN TRANSACTION;
SELECT *
  FROM Fil
  WHERE [Branch ID] = 'B001';
COMMIT TRANSACTION;

SELECT *
  FROM Fil
  WHERE [Branch ID] = 'B001';

--P4
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ;

BEGIN TRANSACTION;
SELECT *
  FROM Fil
  WHERE [Branch ID] = 'B001';
COMMIT TRANSACTION;

SELECT *
  FROM Fil
  WHERE [Branch ID] = 'B001';

--P5
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

BEGIN TRANSACTION;
SELECT *
  FROM Fil
  WHERE [Branch ID] = 'B001';
COMMIT TRANSACTION;

SELECT *
  FROM Fil
  WHERE [Branch ID] = 'B001';

